### ISSUE TITLE
"Assertion failed" error after "npm run dev"

### ISSUE THREAD

**Issue by heba74** [PDFTron/webviewer-mendix-sample#2]
Hi,
I follow the instructions to use the WebViewer in my Mendix app. If I execuite "npm run", I get this error:
![image](https://user-images.githubusercontent.com/26019143/165951303-e2f7448a-f20d-47cc-b93d-40b56626287d.png)
Any idea why this fails?

Best Regads,
Henning

**Comment by andreysaf** [comment]
Hi Henning, thanks for reaching out! 

Could you delete the `node_modules` and then run `npm i` and then `npm run dev` to see if it occurs again?
